replicas: 1

worker:
  replicas: 1

image:
  repository: ghcr.io/goauthentik/server
  tag: 2023.4.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: authentik.domain.tld
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  log_level: debug
  secret_key: 5up3r53cr37K3y
  postgresql:
    password: au7h3n71k
  redis:
    password: au7h3n71k

postgresql:
  enabled: true
  postgresqlPassword: au7h3n71k
  persistence:
    enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: au7h3n71k

blueprints:
  - authentik-ci-blueprint
